stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal
  CI_REGISTRY: mohs.dhcp.lbl.gov
  CONTAINER_IMAGE: $CI_REGISTRY/testing_base:master

image: $CONTAINER_IMAGE

marble_mini_build:
  stage: build
  script:
    - make marble_mini && make marble_mini_clean

marble_build:
  stage: build
  script:
    - make && make clean

sim_build:
  stage: build
  script:
    - make sim && make sim_clean

nucleo_build:
  stage: build
  script:
    - make nucleo && make clean
