/*
 * File: mailbox_def.h
 * Date: 2023-01-05
 * Desc: Header file for Mailbox_Def. Auto-generated by mkmbox.py.
 */

#ifndef __MAILBOX_DEF_H_
#define __MAILBOX_DEF_H_

#ifdef __cplusplus
 extern "C" {
#endif

typedef enum {
  MB2_FMC_MGT_CTL,
} PAGE2_ENUM;

typedef enum {
  MB3_COUNT_HI,
  MB3_COUNT_LO,
  MB3_PAD1,
  MB3_PAD2,
  MB3_LM75_0_HI,
  MB3_LM75_0_LO,
  MB3_LM75_1_HI,
  MB3_LM75_1_LO,
  MB3_FMC_ST,
  MB3_PWR_ST,
  MB3_MGTMUX_ST,
  MB3_PAD3,
  MB3_GIT32_4,
  MB3_GIT32_3,
  MB3_GIT32_2,
  MB3_GIT32_1,
} PAGE3_ENUM;

typedef enum {
  MB4_MAX_T1_HI,
  MB4_MAX_T1_LO,
  MB4_MAX_T2_HI,
  MB4_MAX_T2_LO,
  MB4_MAX_F1_TACH,
  MB4_MAX_F2_TACH,
  MB4_MAX_F1_DUTY,
  MB4_MAX_F2_DUTY,
  MB4_COUNT_HI,
  MB4_COUNT_LO,
} PAGE4_ENUM;


#ifdef __cplusplus
}
#endif

#endif /* __MAILBOX_DEF_H_ */
