# Configuration makefile for projects involving NXP's LPC chips
# Copyright (C) 2013  Richard Meadows
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

PROJECT_NAME  := STM32F2
CHIP	      := STM32f2
OCD_CONF      := stm32f207.cfg
#OCD_CONF      := lpc1776.cfg

# Memory Sizes - Only used for information
ROM_SIZE      := 256K
RAM_SIZE      := 128K

# Compiliation Flags
FLAGS	      := -g3 -ggdb -DXRP_AUTOBOOT

MARBLEM_V1 := board_support/marblemini_v1
MARBLE_V2 := Src

LPCO_SRC   := $(MARBLEM_V1)/lpcopen_2_10/lpc_chip_177x_8x/src
LPCO_INC   := $(MARBLEM_V1)/lpcopen_2_10/lpc_chip_177x_8x/inc
STM_SRC    := Drivers/STM32F2xx_HAL_Driver/Src
STM_INC    := Drivers/STM32F2xx_HAL_Driver/Inc Drivers/CMSIS/Device/ST/STM32F2xx/Include Drivers/CMSIS/Include

# Any sources that do not reside in the source tree
#OTHER_SOURCES := $(MARBLEM_V1)/startup_LPC17xx.c $(MARBLEM_V1)/marble_board.c $(LPCO_SRC)/sysinit_17xx_40xx.c $(LPCO_SRC)/chip_17xx_40xx.c $(LPCO_SRC)/clock_17xx_40xx.c $(LPCO_SRC)/sysctl_17xx_40xx.c $(LPCO_SRC)/uart_17xx_40xx.c $(LPCO_SRC)/ring_buffer.c $(LPCO_SRC)/i2c_17xx_40xx.c $(LPCO_SRC)/ssp_17xx_40xx.c $(LPCO_SRC)/enet_17xx_40xx.c

OTHER_SOURCES := startup/startup_stm32f207xx.s $(MARBLE_V2)/stm32f2xx_hal_msp.c $(MARBLE_V2)/stm32f2xx_it.c $(MARBLE_V2)/system_stm32f2xx.c $(MARBLE_V2)/marble_board.c $(MARBLE_V2)/syscalls.c $(STM_SRC)/stm32f2xx_hal.c $(STM_SRC)/stm32f2xx_hal_cortex.c $(STM_SRC)/stm32f2xx_hal_uart.c $(STM_SRC)/stm32f2xx_hal_gpio.c $(STM_SRC)/stm32f2xx_hal_rcc.c $(STM_SRC)/stm32f2xx_hal_i2c.c $(STM_SRC)/stm32f2xx_hal_eth.c $(STM_SRC)/stm32f2xx_hal_spi.c $(STM_SRC)/stm32f2xx_hal_dma.c

# Local directories to seach for include files
#INCLUDES      := inc $(MARBLEM_V1) $(LPCO_INC)
INCLUDES      := Inc $(MARBLE_V2) $(STM_INC)


# Linker scripts
#LINKERS	      := $(MARBLEM_V1)/mem.ld $(MARBLEM_V1)/sections.ld
LINKERS	      := STM32F207VCTx_FLASH.ld

# Linker Flags
LINKER_FLAGS  := -lc -lnosys -Wl,--gc-sections -specs=nano.specs -specs=nosys.specs

# Debug Driver options
#
# Uncomment the relevant debug driver
#

# LPC11xx and LPC13xx
#DEBUG 	  := crt_emu_lpc11_13_nxp
# LPC17xx (and others?)
DEBUG	  := crt_emu_cm3_nxp
# LPC18xx and LPC43xx
#DEBUG	  := crt_emu_lpc18_43_nxp

# Architecture options
#
# Uncomment the relevant set of flags for your architecture.
#

# Cortex M0+
#ARCH_FLAGS	:= -mthumb -mcpu=cortex-m0plus -march=armv6-m
# Cortex M0
#ARCH_FLAGS	:= -mthumb -mcpu=cortex-m0 -march=armv6-m
# Cortex M1
#ARCH_FLAGS	:= -mthumb -mcpu=cortex-m1 -march=armv6-m
# Cortex M3
ARCH_FLAGS	:= -mthumb -mcpu=cortex-m3 -march=armv7-m
# Cortex M4 (No Floating Point Support)
#ARCH_FLAGS 	:= -mthumb -mcpu=cortex-m4 -march=armv7e-m
# Cortex M4 (Soft Floating Point Support)
#ARCH_FLAGS 	:= -mthumb -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=softfp -mfpu=fpv4-sp-d16
# Cortex M4 (Hard Floating Point Support)
#ARCH_FLAGS 	:= -mthumb -mcpu=cortex-m4 -march=armv7e-m -mfloat-abi=hard -mfpu=fpv4-sp-d16
