/*
 * File: test.h
 * Date: 2023-01-10
 * Desc: Header file for test. Auto-generated by scripts/mkmbox.py.
 */

#ifndef __TEST_H_
#define __TEST_H_

#ifdef __cplusplus
 extern "C" {
#endif

/* ============= DO NOT EDIT THIS AUTO-GENERATED FILE DIRECTLY ============== */
/* ============== Define mailbox structure in scripts/mbox.def ============== */


void mailbox_update_input(void);
void mailbox_update_output(void);


#ifdef __cplusplus
}
#endif

#endif /* __TEST_H_ */
