/*
 * File: mailbox_def.h
 * Desc: Header file for inc/mailbox_def. Auto-generated by scripts/mkmbox.py.
 */

#ifndef __MAILBOX_DEF_H_
#define __MAILBOX_DEF_H_

#ifdef __cplusplus
 extern "C" {
#endif

/* ============= DO NOT EDIT THIS AUTO-GENERATED FILE DIRECTLY ============== */
/* ============== Define mailbox structure in scripts/mbox.def ============== */

typedef enum {
  MB2_FMC_MGT_CTL,
  MB2_SIZE // 1
} PAGE2_ENUM;

typedef enum {
  MB3_COUNT_1,
  MB3_COUNT_0,
  MB3_PAD1,
  MB3_PAD2,
  MB3_LM75_0_1,
  MB3_LM75_0_0,
  MB3_LM75_1_1,
  MB3_LM75_1_0,
  MB3_FMC_ST,
  MB3_PWR_ST,
  MB3_MGTMUX_ST,
  MB3_PAD3,
  MB3_GIT32_3,
  MB3_GIT32_2,
  MB3_GIT32_1,
  MB3_GIT32_0,
  MB3_SIZE // 13
} PAGE3_ENUM;

typedef enum {
  MB4_MAX_T1_HI,
  MB4_MAX_T1_LO,
  MB4_MAX_T2_HI,
  MB4_MAX_T2_LO,
  MB4_MAX_F1_TACH,
  MB4_MAX_F2_TACH,
  MB4_MAX_F1_DUTY,
  MB4_MAX_F2_DUTY,
  MB4_PCB_REV,
  MB4_COUNT_1,
  MB4_COUNT_0,
  MB4_SIZE // 11
} PAGE4_ENUM;

typedef enum {
  MB5_I2C_BUS_STATUS,
  MB5_SIZE // 1
} PAGE5_ENUM;

typedef enum {
  MB16_PMOD_CR0_0,
  MB16_PMOD_CR0_1,
  MB16_PMOD_CR0_2,
  MB16_PMOD_CR0_3,
  MB16_PMOD_CR0_4,
  MB16_PMOD_CR0_5,
  MB16_PMOD_CR0_6,
  MB16_PMOD_CR0_7,
  MB16_PMOD_CR0_8,
  MB16_PMOD_CR0_9,
  MB16_PMOD_CR0_10,
  MB16_PMOD_CR0_11,
  MB16_PMOD_CR0_12,
  MB16_PMOD_CR0_13,
  MB16_PMOD_CR0_14,
  MB16_PMOD_CR0_15,
  MB16_SIZE // 16
} PAGE16_ENUM;

typedef enum {
  MB17_PMOD_DATA_PAGE0_0,
  MB17_PMOD_DATA_PAGE0_1,
  MB17_PMOD_DATA_PAGE0_2,
  MB17_PMOD_DATA_PAGE0_3,
  MB17_PMOD_DATA_PAGE0_4,
  MB17_PMOD_DATA_PAGE0_5,
  MB17_PMOD_DATA_PAGE0_6,
  MB17_PMOD_DATA_PAGE0_7,
  MB17_PMOD_DATA_PAGE0_8,
  MB17_PMOD_DATA_PAGE0_9,
  MB17_PMOD_DATA_PAGE0_10,
  MB17_PMOD_DATA_PAGE0_11,
  MB17_PMOD_DATA_PAGE0_12,
  MB17_PMOD_DATA_PAGE0_13,
  MB17_PMOD_DATA_PAGE0_14,
  MB17_PMOD_DATA_PAGE0_15,
  MB17_SIZE // 16
} PAGE17_ENUM;


void mailbox_update_input(void);
void mailbox_update_output(void);
void mailbox_read_print_all(void);


#ifdef __cplusplus
}
#endif

#endif /* __MAILBOX_DEF_H_ */
