/*  file: uart_fifo.h
 *  Author: Auto-generated by mkqueue.py
 */

#ifndef __UART_FIFO_H
#define __UART_FIFO_H

#ifdef __cplusplus
extern "C" {
#endif

// ================================= Includes ==================================
#include <stdio.h>
#include <stdint.h>

// ============================== Exported Macros ==============================
#define UART_QUEUE_ITEMS                            (100)
#define UART_QUEUE_OK                              (0x00)
#define UART_QUEUE_FULL                            (0x01)
#define UART_QUEUE_EMPTY                           (0x02)

#define UART_DATA_NOT_LOST                            (0)
#define UART_DATA_LOST                                (1)

// ============================= Exported Typedefs =============================

// ======================= Exported Function Prototypes ========================
void UARTQUEUE_Init(void);
uint8_t UARTQUEUE_Add(uint8_t *item);
uint8_t UARTQUEUE_Get(volatile uint8_t *item);
uint8_t UARTQUEUE_Status(void);
int UARTQUEUE_ShiftOut(uint8_t *pData, int len);
void UARTQUEUE_SetDataLost(uint8_t lost);
uint8_t UARTQUEUE_IsDataLost(void);

#ifdef __cplusplus
}
#endif

#endif // __UART_FIFO_H

