build:
  variables:
    # From Gitlab documentation:
    # Configure a network with container links GitLab Runner before
    # 18.7.0 uses the default Docker bridge along with legacy
    # container links to link the job container with the services.
    # Because Docker deprecated the links functionality, in GitLab
    # Runner 18.7.0 and later, the legacy container link behavior
    # is emulated by allowing service aliases to be resolved using
    # Docker’s extra_hosts functionality. This network mode is the
    # default if FF_NETWORK_PER_BUILD is disabled.
    FF_NETWORK_PER_BUILD: "true"
  services:
    - name: mohs.dhcp.lbl.gov/docker:29.4.0-dind
      command: ["--insecure-registry", "mohs.dhcp.lbl.gov"]
      alias: docker
  image: docker:stable
  stage: pre-build
  before_script:
    - cat /etc/hosts
    - cat /etc/resolv.conf
    - docker info
    - echo $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME
    - echo $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
    - echo $CONTAINER_IMAGE:$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA
  script: |
    docker pull $CONTAINER_IMAGE:latest || true
    docker build --cache-from $CONTAINER_IMAGE:latest \
        -t $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME \
        -t $CONTAINER_IMAGE:$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA \
        -t $CONTAINER_IMAGE:latest \
        .
    docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_NAME
    docker push $CONTAINER_IMAGE:$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA
    docker push $CONTAINER_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_COMMIT_BRANCH
      changes:
        - Dockerfile*
        - .gitlab/ci/build.gitlab-ci.yml
